# Используем официальный образ Go
FROM golang:1.24.1-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum для загрузки зависимостей
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Копируем исходный код
COPY backend/ ./

# Компилируем приложение
RUN go build -o main .

# Указываем порт
EXPOSE 8080

# Команда для запуска приложения
CMD ["./main"]